<?php

namespace App\Service;

use App\Entity\Scan;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Process\Process;
use Symfony\Contracts\HttpClient\HttpClientInterface;

class GitIntegrationService
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
        private readonly AiFixService $aiFixService,
        private readonly HttpClientInterface $httpClient,
    ) {
    }

    /**
     * Applique les remediations (fixes AI + documentation) dans une branche dédiée,
     * pousse vers le dépôt distant et ouvre une Pull Request si GIT_TOKEN est configuré.
     *
     * @return array{branch: ?string, prUrl: ?string}
     */
    public function applyAndPush(Scan $scan, string $workdir): array
    {
        $remediations = $this->collectPendingRemediations($scan);

        if (\count($remediations) === 0) {
            return ['branch' => null, 'prUrl' => null];
        }

        $shortUuid = substr($scan->getId(), 0, 8);
        $branchName = sprintf('fix/securescan-%s-%s', date('Y-m-d'), $shortUuid);

        $this->injectTokenInRemoteUrl($workdir);
        $this->configureGitIdentity($workdir);
        $this->unshallowIfNeeded($workdir);
        $this->createBranch($workdir, $branchName);

        $this->applyAiFixes($workdir, $remediations);
        $this->writeRemediationFiles($workdir, $remediations);

        $this->commitChanges($workdir, $scan);
        $this->pushBranch($workdir, $branchName);

        $repoUrl = $scan->getProject()->getRepositoryUrl();
        $prUrl = $this->createPullRequest($repoUrl, $branchName, $scan);

        foreach ($remediations as $remediation) {
            $remediation->setStatus('applied');
            $remediation->setGitBranchName($branchName);
            if ($prUrl !== null) {
                $remediation->setPrUrl($prUrl);
            }
            $remediation->setUpdatedAt(new \DateTime());
        }

        $this->entityManager->flush();

        return ['branch' => $branchName, 'prUrl' => $prUrl];
    }

    private const MAX_AI_FIXES = 10;

    private const SEVERITY_PRIORITY = [
        'CRITICAL' => 0,
        'HIGH' => 1,
        'MEDIUM' => 2,
        'LOW' => 3,
        'INFO' => 4,
    ];

    /**
     * Applies AI-generated fixes directly to source files in the workdir.
     *
     * Limited to MAX_AI_FIXES calls to avoid API rate limits and keep PRs reviewable.
     * Findings are prioritized by severity (CRITICAL first).
     */
    private function applyAiFixes(string $workdir, array $remediations): void
    {
        // Sort by severity so the most critical findings get AI fixes first
        $candidates = $remediations;
        usort($candidates, function ($a, $b) {
            $sevA = self::SEVERITY_PRIORITY[strtoupper($a->getFinding()->getSeverity())] ?? 5;
            $sevB = self::SEVERITY_PRIORITY[strtoupper($b->getFinding()->getSeverity())] ?? 5;
            return $sevA <=> $sevB;
        });

        $applied = 0;

        foreach ($candidates as $remediation) {
            if ($applied >= self::MAX_AI_FIXES) {
                break;
            }

            $finding = $remediation->getFinding();
            $filePath = $finding->getFilePath();
            $rawCode = $finding->getRawCode();

            if ($filePath === '' || $rawCode === null || trim($rawCode) === '') {
                continue;
            }

            $fullPath = $workdir . '/' . $filePath;
            if (!file_exists($fullPath)) {
                continue;
            }

            $fixedCode = $this->aiFixService->generateFix($finding);
            if ($fixedCode === null || trim($fixedCode) === '') {
                continue;
            }

            $fileContent = file_get_contents($fullPath);
            if ($fileContent === false) {
                continue;
            }

            // Replace the vulnerable code snippet with the AI-generated fix
            $newContent = str_replace(trim($rawCode), $fixedCode, $fileContent);
            if ($newContent !== $fileContent) {
                file_put_contents($fullPath, $newContent);
                $applied++;
            }
        }
    }

    /**
     * Creates a Pull Request on GitHub via the API.
     *
     * Returns the PR URL on success, or null if the token is missing or the call fails.
     */
    private function createPullRequest(string $repoUrl, string $branchName, Scan $scan): ?string
    {
        $token = $_ENV['GIT_TOKEN'] ?? $_SERVER['GIT_TOKEN'] ?? '';
        if ($token === '') {
            return null;
        }

        $ownerRepo = $this->parseOwnerRepo($repoUrl);
        if ($ownerRepo === null) {
            return null;
        }

        [$owner, $repo] = $ownerRepo;

        $title = sprintf('[SecureScan] Security fixes for scan %s', substr($scan->getId(), 0, 8));
        $body = sprintf(
            "Automated security remediations generated by SecureScan.\n\n"
            . "**Scan score:** %s/100\n"
            . "**Findings:** %d\n\n"
            . "This PR contains AI-generated code fixes and remediation documentation.",
            $scan->getGlobalScore() ?? 'N/A',
            $scan->getFindings()->count()
        );

        // Detect the default branch to use as base
        $baseBranch = $this->detectDefaultBranch($owner, $repo, $token);

        try {
            $response = $this->httpClient->request('POST', sprintf('https://api.github.com/repos/%s/%s/pulls', $owner, $repo), [
                'headers' => [
                    'Authorization' => sprintf('Bearer %s', $token),
                    'Accept' => 'application/vnd.github+json',
                ],
                'json' => [
                    'title' => $title,
                    'body' => $body,
                    'head' => $branchName,
                    'base' => $baseBranch,
                ],
            ]);

            $data = $response->toArray();

            return $data['html_url'] ?? null;
        } catch (\Throwable) {
            return null;
        }
    }

    /**
     * Detects the default branch of a GitHub repository.
     */
    private function detectDefaultBranch(string $owner, string $repo, string $token): string
    {
        try {
            $response = $this->httpClient->request('GET', sprintf('https://api.github.com/repos/%s/%s', $owner, $repo), [
                'headers' => [
                    'Authorization' => sprintf('Bearer %s', $token),
                    'Accept' => 'application/vnd.github+json',
                ],
            ]);

            $data = $response->toArray();

            return $data['default_branch'] ?? 'main';
        } catch (\Throwable) {
            return 'main';
        }
    }

    /**
     * Extracts owner and repo name from a GitHub URL.
     *
     * Supports: https://github.com/owner/repo, https://github.com/owner/repo.git
     *
     * @return array{0: string, 1: string}|null
     */
    private function parseOwnerRepo(string $repoUrl): ?array
    {
        if (preg_match('#github\.com[/:]([^/]+)/([^/.]+?)(?:\.git)?$#', $repoUrl, $matches)) {
            return [$matches[1], $matches[2]];
        }

        return null;
    }

    private function collectPendingRemediations(Scan $scan): array
    {
        $remediations = [];

        foreach ($scan->getFindings() as $finding) {
            $remediation = $finding->getRemediation();
            if ($remediation === null) {
                continue;
            }

            if ($remediation->getStatus() !== 'pending') {
                continue;
            }

            $proposedFix = $remediation->getProposedFix();
            if ($proposedFix === null || trim($proposedFix) === '') {
                continue;
            }

            $remediations[] = $remediation;
        }

        return $remediations;
    }

    private function injectTokenInRemoteUrl(string $workdir): void
    {
        $token = $_ENV['GIT_TOKEN'] ?? $_SERVER['GIT_TOKEN'] ?? '';
        if ($token === '') {
            return;
        }

        $process = new Process(['git', 'remote', 'get-url', 'origin'], $workdir);
        $process->run();
        $currentUrl = trim($process->getOutput());

        if ($currentUrl === '' || !str_starts_with($currentUrl, 'https://')) {
            return;
        }

        $authenticatedUrl = preg_replace(
            '#^https://#',
            sprintf('https://x-access-token:%s@', $token),
            $currentUrl
        );

        $this->runGit(['git', 'remote', 'set-url', 'origin', $authenticatedUrl], $workdir);
    }

    private function configureGitIdentity(string $workdir): void
    {
        $this->runGit(['git', 'config', 'user.email', 'securescan-bot@securescan.local'], $workdir);
        $this->runGit(['git', 'config', 'user.name', 'SecureScan Bot'], $workdir);
    }

    private function unshallowIfNeeded(string $workdir): void
    {
        if (file_exists($workdir . '/.git/shallow')) {
            $process = new Process(['git', 'fetch', '--unshallow'], $workdir);
            $process->setTimeout(300);
            $process->run();
        }
    }

    private function createBranch(string $workdir, string $branchName): void
    {
        $this->runGit(['git', 'checkout', '-b', $branchName], $workdir);
    }

    private function writeRemediationFiles(string $workdir, array $remediations): void
    {
        $fixDir = $workdir . '/.securescan';
        if (!is_dir($fixDir)) {
            @mkdir($fixDir, 0777, true);
        }

        foreach ($remediations as $remediation) {
            $finding = $remediation->getFinding();
            $safeFilename = preg_replace('/[^a-zA-Z0-9_\-]/', '_', basename($finding->getFilePath()));
            $filename = sprintf('fix-%s-%s.md', $safeFilename, substr($finding->getId(), 0, 8));

            $content = $this->buildRemediationMarkdown($finding, $remediation);
            file_put_contents($fixDir . '/' . $filename, $content);
        }
    }

    private function buildRemediationMarkdown($finding, $remediation): string
    {
        $lines = [];
        $lines[] = '# SecureScan Remediation';
        $lines[] = '';
        $lines[] = sprintf('**Severity:** %s', $finding->getSeverity());
        $lines[] = sprintf('**Tool:** %s', $finding->getToolSource());
        $lines[] = sprintf('**File:** `%s`', $finding->getFilePath());

        if ($finding->getLineNumber() !== null) {
            $lines[] = sprintf('**Line:** %d', $finding->getLineNumber());
        }

        if ($finding->getOwaspCategory() !== null) {
            $lines[] = sprintf('**OWASP Category:** %s', $finding->getOwaspCategory());
        }

        $lines[] = '';
        $lines[] = '## Description';
        $lines[] = '';
        $lines[] = $finding->getDescription();
        $lines[] = '';
        $lines[] = '## Proposed Fix';
        $lines[] = '';
        $lines[] = $remediation->getProposedFix();
        $lines[] = '';

        if ($finding->getRawCode() !== null && $finding->getRawCode() !== '') {
            $lines[] = '## Raw Code';
            $lines[] = '';
            $lines[] = '```';
            $lines[] = $finding->getRawCode();
            $lines[] = '```';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function commitChanges(string $workdir, Scan $scan): void
    {
        $this->runGit(['git', 'add', '-A'], $workdir);

        $message = sprintf(
            "[SecureScan] Security remediations for scan %s\n\nAutomated security fix documentation generated by SecureScan.\nScan score: %s/100\nFindings: %d",
            substr($scan->getId(), 0, 8),
            $scan->getGlobalScore() ?? 'N/A',
            $scan->getFindings()->count()
        );

        $this->runGit(['git', 'commit', '-m', $message], $workdir);
    }

    private function pushBranch(string $workdir, string $branchName): void
    {
        $token = $_ENV['GIT_TOKEN'] ?? $_SERVER['GIT_TOKEN'] ?? '';
        if ($token === '') {
            return;
        }

        $process = new Process(['git', 'push', '-u', 'origin', $branchName], $workdir);
        $process->setTimeout(120);
        $process->run();

        if (!$process->isSuccessful()) {
            throw new \RuntimeException(
                'Git push failed: ' . $process->getErrorOutput()
            );
        }
    }

    private function runGit(array $command, string $workdir): void
    {
        $process = new Process($command, $workdir);
        $process->setTimeout(60);
        $process->run();

        if (!$process->isSuccessful()) {
            throw new \RuntimeException(
                sprintf('Git command failed [%s]: %s', implode(' ', $command), $process->getErrorOutput())
            );
        }
    }
}
